openapi: 3.0.0
info:
  title: Exploratory Demo API
  version: draft
  description: Simple API to demo the API Builder in Postman
  contact:
    name: Arlemi Turpault
    email: arlemi@postman.com
servers:
  - url: https://2226c84a-4865-4f09-bac5-d97640dfd2b7.mock.pstmn.io
    description: Demo API
paths:
  /videos:
    get:
      operationId: allVideos
      summary: returns an array of videos 
      description: Returns a list of all the Exploratory videos
      tags:
      - videos
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/video"
  /videos/{videoId}:
    get:
      operationId: oneVideo
      summary: video request
      description: showing how to get video from an endpoint
      tags:                                            
        - videos
      parameters:
      - name: videoId
        in: path
        required: true
        schema:
          type: number
          example: 4
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/video" 
components:
  schemas:
    video:
      type: object
      properties:
        name:
          type: string
          description: Video title
          example: "Public Workspaces"
        url:
          type: string
          description: Video URL
          example: "https://www.youtube.com/watch?v=DjGbMdqnY64"
        views:
          type: number
          description: Number of views
          example: 7483

tags:
  - name: videos
    description: API returning info about Exploratory videos